
epochs = range(1, len(custom_model_history.history['loss']) + 1)

plt.plot(epochs, custom_model_history.history['loss'], 'y', label='Training loss')
plt.plot(epochs, custom_model_history.history['val_loss'], 'r', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()


plt.plot(epochs, custom_model_history.history['accuracy'], 'y', label='Training acc')
plt.plot(epochs, custom_model_history.history['val_accuracy'], 'r', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

plt.plot(epochs, custom_model_history.history['precision'], 'y', label='Training acc')
plt.plot(epochs, custom_model_history.history['val_precision'], 'r', label='Validation acc')
plt.title('Training and validation precision')
plt.xlabel('Epochs')
plt.ylabel('Precision')
plt.legend()
plt.show()

plt.plot(epochs, custom_model_history.history['recall'], 'y', label='Training acc')
plt.plot(epochs, custom_model_history.history['val_recall'], 'r', label='Validation acc')
plt.title('Training and validation recall')
plt.xlabel('Epochs')
plt.ylabel('Recall')
plt.legend()
plt.show()

plt.plot(epochs, custom_model_history.history['specificity'], 'y', label='Training acc')
plt.plot(epochs, custom_model_history.history['val_specificity'], 'r', label='Validation acc')
plt.title('Training and validation specificity')
plt.xlabel('Epochs')
plt.ylabel('Specificity')
plt.legend()
plt.show()

plt.plot(epochs, custom_model_history.history['f1_score'], 'y', label='Training acc')
plt.plot(epochs, custom_model_history.history['val_f1_score'], 'r', label='Validation acc')
plt.title('Training and validation f1_score')
plt.xlabel('Epochs')
plt.ylabel('F1_score')
plt.legend()
plt.show()
